# Where on the system to persist the oxigraph store folder
store_path: "/tmp/triplestar_kb"

# Whether to clear the store at startup
clear_on_startup: true

# Base IRI for resolving relative IRIs and functions in the KB
base_iri: "https://coresense.eu/understanding"

# Turtle files to load at startup
preload_files:
  - sysml2.ttl
  - iso.ttl
  - cso.ttl
  - uao.ttl
  - understanding.ttl
  - decision_scenario.ttl
