PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cso: <https://github.com/CoreSenseEU/CoreSense/blob/main/models/ontology/coresense_ontologies/CSO/cso.sysml#>
PREFIX csu: <https://github.com/CoreSenseEU/coresense_understanding_bringup/blob/main/preload/understanding.ttl#>

SELECT *
WHERE {
  ?modelet_id rdf:type cso:Modelet;
    csu:hasFormalism ?formalism.
  OPTIONAL { ?modelet csu:modelsConcept ?concept. }
  OPTIONAL { ?modelet csu:hasRepresentationClass ?representationClass. }
  OPTIONAL {
    ?modelet csu:hasProperty ?property.
    ?property csu:hasClass ?propertyClass;
       csu:hasValue ?propertyValue.
  }
}

#  OPTIONAL { ?modelet csu:hasCreator ?creator. }
#  OPTIONAL { ?modelet csu:hasLocation ?location. }
#  OPTIONAL { ?modelet csu:hasScope ?scope. }
